version: "3.9"
   
services:
  db:
    image: postgres
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"

  syncworker:
    build: 
      context: .
      dockerfile: Dockerfile.SyncWorker
    depends_on:
      - db
    #restart: always
  
  web:
    build: 
      context: .
      dockerfile: Dockerfile.WebApi
    ports:
      - "5000:80"
    depends_on:
      - db
      - syncworker
    #restart: always
    